/***********************************************                         
  DO NOT MODIFY THE CONTENTS OF THIS FILE.                              
  This header file has been auto-generated by ncelab.                        
  This should be included in user'c C file to                        
  facilitate the calling of exported tasks and functions.                        
************************************************/                        

#include "svdpi.h" 

#ifdef __cplusplus                          
    extern "C" {                          
#endif 

typedef struct { 
	char _a0;
 	int _a1;
 	int _a2;
 } tb__mem_packet_t;


#ifdef __cplusplus                          
 }                          
#endif

